### ISSUE TITLE
GET http://localhost:3000/bundle.js 

### ISSUE THREAD

**Issue by thomcchester** [Ice32/blog-MERN#1]
Hey, I am new to MERN I am trying to switch over from MEAN. I tried starting up your app here and have run into some issues. I have everything installed and up and running, have listening on port 3000 etc but when I look at the page there is nothing and console only shows (http://localhost:3000/bundle.js /localhost:28 GET http://localhost:3000/bundle.js ). Wondering if you might know that going on.

**Comment by Ice32** [comment]
@thomcchester Hello, sorry for not replying earlier.

Did you bundle the app using the webpack command?  That might be the issue.

Also, babel-core package is required now (it wasn't at the time when this app was written), so make sure to include it too.

So, the commands I'm suggesting are:
cd blog-MERN
npm install --save babel-core
npm install -g webpack
webpack
npm start

**Comment by thomcchester** [comment]
Thanks man that worked perfectly!

**Comment by Ice32** [comment]
@thomcchester Glad to hear that
